dbt_mf_bq:
  outputs:
    dev:
      dataset: dbt_ssahoo
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /root/dev-data-pipelines.json
      location: EU
      method: service-account
      priority: interactive
      project: cnm-env-dev
      threads: 1
      type: bigquery
  target: dev
lessions:
  outputs:
    dev:
      dataset: dbt_sks
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: cnm-env-datasandbox
      threads: 60
      type: bigquery
  target: dev
